### PR TITLE
backend: add request parameter to authenticate

### PR DESCRIPTION
**Pull request by guhl**
otherwhise inspect.getcallargs(backend.authenticate, request, **credentials) fails in contrib.auth.authenticate.

Using django 2.1.2, python 3.6.5

### CODE REVIEW

**Comment by cnobile2012** [comment]
Hey, I think you need to update your repo, those changes were made to my code base a long time ago. I did it a little differently than you did but it should work fine for you the way it is. I'm going to write a few more unittests though.

**Comment by guhl** [comment]
I did update the repo (that is the fcfabe4125070e5a42c173acbcc9c99734047130 commit)

The only thing I hat to change now is the change from
def authenticate(self, username=None, password=None, **extra_fields):
to 
def authenticate(self, request=None, username=None, password=None, service='login', **extra_fields):

in django_pam/auth/backends.py

Without that the inspect.getcallargs(backend.authenticate, request, **credentials) that is called in contrib.auth.authenticate fails throwing a TypeError because it gets confused with the number of args.

Might be specific to my django/python version but i can replicate this on my development machine and my production server.

**Comment by cnobile2012** [comment]
OK, I see what you are talking about. I just read the Release Notes for Django 2.1. I was still using 2.0.5 in my tests, so I upgraded. I found this error when I ran my unit tests and needed to fix it in the forms.py also.

You have the 'service' keyword argument passed into the method also, but I have done this using the **extra_fields argument. This is what I need to write the other unit tests for. I'm not sure I did this correct.

So at this point, I want to write those tests first before I merge your pull request.

**Comment by cnobile2012** [comment]
OK, so I wrote the additional unit tests and everything is now passing, however, since you had added some code that fixed a previous bug differently than I fixed it I couldn't use your pull request. I had not only added the 'service' keyword, but I also added the 'encoding' and 'resetcreds' keywords.

It's a good idea to run the unit tests to see everything that breaks so that your pull request can be as complete as possible.

I do, however, thank you for the heads up on this issue.

**Comment by guhl** [comment]
Dear Carl,

thanks for picking that up and fixing it. I will stash my changes and update my repo from yours.
My intention is not to have my pull requests merged but to show that there is a problem and how I worked around it.

Thanks again - Guhl

**Pull request closed without merging**
